version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres-3
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  movie-service:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db-data: